Legalize aten.repeat_interleave.Tensor for torch-mlir
Xilinx/torch-mlir pull request #44
Opened 2023-05-30 10:27 UTC by flemairen6

2023-05-30 11:22 UTC, mgehre-amd requested changes

2023-05-30 11:22 UTC, mgehre-amd commented on python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/abstract_interp_lib_gen.py
> +    return repeats
Isn't the output size somehow depending on the sum of entries in `repeats`? At least this is how I read https://pytorch.org/docs/stable/generated/torch.repeat_interleave.html#torch.repeat_interleave

2023-05-30 11:22 UTC, mgehre-amd commented on python/torch_mlir_e2e_test/test_suite/basic.py
> +        x = torch.ops.aten.repeat_interleave(x, output_size=10)
```suggestion
        x = torch.ops.aten.repeat_interleave(x, output_size=10)
        y = torch.ops.aten.repeat_interleave(x)
        return x, y
```
Can you add another call without the optional output_size here?

2023-05-30 14:42 UTC, mgehre-amd commented
Seems like you need to mark the test as XFAIL for LTC

2023-05-30 15:50 UTC, ttjost approved these changes
Thanks!

2023-05-30 18:20 UTC, mgehre-amd commented
Seems like you also have to mark linalg backend as xfail for now

2023-05-31 09:50 UTC, mgehre-amd approved these changes

2023-05-31 09:50 UTC, merged